# Generated by Django 6.1.2 on 2026-10-08 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tfl", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="block",
            name="tfl_block_base_ve_f26d8d_idx",
        ),
        migrations.RemoveIndex(
            model_name="journey",
            name="tfl_journey_base_ve_2e5c12_idx",
        ),
        migrations.RemoveIndex(
            model_name="pattern",
            name="tfl_pattern_base_ve_97c20f_idx",
        ),
        migrations.RemoveIndex(
            model_name="stopinpattern",
            name="tfl_stopinp_base_ve_573a4f_idx",
        ),
        migrations.AddField(
            model_name="journey",
            name="block",
            field=models.ForeignObject(
                from_fields=["base_version", "block_idx"],
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tfl.block",
                to_fields=["base_version", "idx"],
            ),
        ),
        migrations.AddField(
            model_name="journey",
            name="pattern",
            field=models.ForeignObject(
                from_fields=["base_version", "pattern_idx"],
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tfl.pattern",
                to_fields=["base_version", "idx"],
            ),
        ),
        migrations.AddField(
            model_name="pattern",
            name="line",
            field=models.ForeignObject(
                from_fields=["base_version", "contract_line_no"],
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tfl.line",
                to_fields=["base_version", "contract_line_no"],
            ),
        ),
        migrations.AddField(
            model_name="stopinpattern",
            name="destination",
            field=models.ForeignObject(
                from_fields=["base_version", "destination_idx"],
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tfl.destination",
                to_fields=["base_version", "idx"],
            ),
        ),
        migrations.AddField(
            model_name="stopinpattern",
            name="pattern",
            field=models.ForeignObject(
                from_fields=["base_version", "pattern_idx"],
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tfl.pattern",
                to_fields=["base_version", "idx"],
            ),
        ),
        migrations.AddField(
            model_name="stopinpattern",
            name="stop",
            field=models.ForeignObject(
                from_fields=["base_version", "stop_idx"],
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tfl.stop",
                to_fields=["base_version", "idx"],
            ),
        ),
        migrations.AddConstraint(
            model_name="block",
            constraint=models.UniqueConstraint(
                fields=("base_version", "idx"), name="tfl_block_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="journey",
            constraint=models.UniqueConstraint(
                fields=("base_version", "idx"), name="tfl_journey_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="pattern",
            constraint=models.UniqueConstraint(
                fields=("base_version", "idx"), name="tfl_pattern_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="stopinpattern",
            constraint=models.UniqueConstraint(
                fields=("base_version", "idx"), name="tfl_stopinpattern_unique"
            ),
        ),
    ]
